/* eslint-env jest */
import { render, screen } from "@testing-library/react";
import React from "react";
import LoadingSpinner from "./LoadingSpinner";
/**
 * --- AUTO-GENERATED DOCSTRING ---
 * Table of content is automatically generated by Agent Docstrings v1.3.5
 *
 * Classes/Functions:
 *   - describe('LoadingSpinner', () => (line 18)
 *   - it('renders loading text when provided', () => (line 19)
 *   - render(<LoadingSpinner text="Loading..." />); (line 20)
 *   - expect(spinner).toBeInTheDocument(); (line 22)
 *   - expect(screen.getAllByText('Loading...').length).toBeGreaterThan(0); (line 23)
 * --- END AUTO-GENERATED DOCSTRING ---
 */

describe("LoadingSpinner", () => {
  it("renders loading text when provided", () => {
    render(<LoadingSpinner text="Loading..." />);
    const spinner = screen.getByRole("status");
    expect(spinner).toBeInTheDocument();
    expect(screen.getAllByText("Loading...").length).toBeGreaterThan(0);
  });
});
