/* eslint-env vitest */
/**
 * @module NavBar.test
 * @description Tests for NavBar component theme switching functionality
 */
/**
 * --- AUTO-GENERATED DOCSTRING ---
 * Table of content is automatically generated by Agent Docstrings v1.3.5
 *
 * Classes/Functions:
 *   - describe("NavBar Component", () => (line 63)
 *   - beforeEach(() => (line 75)
 *   - test("renders theme toggle button", () => (line 81)
 *   - render(<NavBar (line 82)
 *   - expect(themeButton).toBeInTheDocument(); (line 86)
 *   - test("theme toggle calls onThemeChange with opposite theme", () => (line 89)
 *   - expect(onThemeChange).toHaveBeenCalledWith(false); (line 104)
 *   - test("theme toggle saves to localStorage", () => (line 107)
 *   - render(<NavBar (line 108)
 *   - expect(localStorageMock.setItem).toHaveBeenCalledWith("theme", "dark"); (line 115)
 *   - test("theme toggle updates meta theme-color", () => (line 118)
 *   - render(<NavBar (line 119)
 *   - expect(mockQuerySelector).toHaveBeenCalledWith("meta[name='theme-color']"); (line 128)
 *   - test("shows correct theme state based on current theme", () => (line 131)
 *   - expect(themeSwitch).toHaveAttribute("aria-checked", "true"); (line 139)
 *   - rerender(<NavBar (line 142)
 *   - expect(themeSwitch).toHaveAttribute("aria-checked", "false"); (line 143)
 *   - test("matrix mode activates after 5 rapid clicks", () => (line 146)
 *   - render(<NavBar (line 148)
 *   - for (let i = 0; i < 5; i++) (line 155)
 *   - expect(onMatrixActivate).toHaveBeenCalled(); (line 159)
 * --- END AUTO-GENERATED DOCSTRING ---
 */

import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import "@testing-library/jest-dom";
import { describe, test, expect, beforeEach, vi } from "vitest";
import NavBar from "./NavBar";

// Mock localStorage
const localStorageMock = {
  getItem: vi.fn(),
  setItem: vi.fn(),
  removeItem: vi.fn(),
  clear: vi.fn(),
};
Object.defineProperty(window, "localStorage", {
  value: localStorageMock,
  writable: true,
});

// Mock document.querySelector for meta theme-color
const mockMetaElement = {
  setAttribute: vi.fn(),
};
const mockQuerySelector = vi.fn(() => mockMetaElement);
Object.defineProperty(document, "querySelector", {
  value: mockQuerySelector,
  writable: true,
});

describe("NavBar Component", () => {
  const defaultProps = {
    view: "tournament",
    setView: vi.fn(),
    isLoggedIn: false,
    userName: "",
    onLogout: vi.fn(),
    onMatrixActivate: vi.fn(),
    isLightTheme: true,
    onThemeChange: vi.fn(),
  };

  beforeEach(() => {
    vi.clearAllMocks();
    localStorageMock.setItem.mockClear();
    mockMetaElement.setAttribute.mockClear();
  });

  test("renders theme toggle button", () => {
    render(<NavBar {...defaultProps} />);
    const themeButton = screen.getByRole("switch", {
      name: /Switch to dark theme/i,
    });
    expect(themeButton).toBeInTheDocument();
  });

  test("theme toggle calls onThemeChange with opposite theme", () => {
    const onThemeChange = vi.fn();
    render(
      <NavBar
        {...defaultProps}
        onThemeChange={onThemeChange}
        isLightTheme={true}
      />
    );

    const themeButton = screen.getByRole("switch", {
      name: /Switch to dark theme/i,
    });
    fireEvent.click(themeButton);

    expect(onThemeChange).toHaveBeenCalledWith(false);
  });

  test("theme toggle saves to localStorage", () => {
    render(<NavBar {...defaultProps} isLightTheme={true} />);

    const themeButton = screen.getByRole("switch", {
      name: /Switch to dark theme/i,
    });
    fireEvent.click(themeButton);

    expect(localStorageMock.setItem).toHaveBeenCalledWith("theme", "dark");
  });

  test("theme toggle updates meta theme-color", () => {
    render(<NavBar {...defaultProps} isLightTheme={true} />);

    const themeButton = screen.getByRole("switch", {
      name: /Switch to dark theme/i,
    });
    fireEvent.click(themeButton);

    // Note: This test is simplified since the meta tag update is handled by the parent App component
    // The NavBar component calls updateThemeColor which attempts to update the meta tag
    expect(mockQuerySelector).toHaveBeenCalledWith("meta[name='theme-color']");
  });

  test("shows correct theme state based on current theme", () => {
    // Test light theme
    const { rerender } = render(
      <NavBar {...defaultProps} isLightTheme={true} />
    );
    const themeSwitch = screen.getByRole("switch", {
      name: /Switch to dark theme/i,
    });
    expect(themeSwitch).toHaveAttribute("aria-checked", "true");

    // Test dark theme
    rerender(<NavBar {...defaultProps} isLightTheme={false} />);
    expect(themeSwitch).toHaveAttribute("aria-checked", "false");
  });

  test("matrix mode activates after 5 rapid clicks", () => {
    const onMatrixActivate = vi.fn();
    render(<NavBar {...defaultProps} onMatrixActivate={onMatrixActivate} />);

    const themeButton = screen.getByRole("switch", {
      name: /Switch to dark theme/i,
    });

    // Click 5 times rapidly
    for (let i = 0; i < 5; i++) {
      fireEvent.click(themeButton);
    }

    expect(onMatrixActivate).toHaveBeenCalled();
  });
});
