import { describe, it, expect } from 'vitest';
import { getContrastRatio, meetsWCAGAA } from './contrastChecker';
/**
 * --- AUTO-GENERATED DOCSTRING ---
 * Table of content is automatically generated by Agent Docstrings v1.3.5
 *
 * Classes/Functions:
 *   - describe('contrastChecker', () => (line 17)
 *   - it('computes correct contrast for black on white', () => (line 18)
 *   - expect(ratio).toBeGreaterThanOrEqual(21); (line 20)
 *   - it('meets AA for sample tokens (light theme)', () => (line 23)
 *   - expect(meetsWCAGAA(ratioBody, 'normal')).toBe(true); (line 25)
 *   - expect(meetsWCAGAA(ratioCardText, 'normal')).toBe(true); (line 28)
 * --- END AUTO-GENERATED DOCSTRING ---
 */

describe('contrastChecker', () => {
  it('computes correct contrast for black on white', () => {
    const ratio = getContrastRatio('#000000', '#ffffff');
    expect(ratio).toBeGreaterThanOrEqual(21);
  });

  it('meets AA for sample tokens (light theme)', () => {
    const ratioBody = getContrastRatio('#111827', '#eef1f6');
    expect(meetsWCAGAA(ratioBody, 'normal')).toBe(true);

    const ratioCardText = getContrastRatio('#111827', '#ffffff');
    expect(meetsWCAGAA(ratioCardText, 'normal')).toBe(true);
  });
});
