/**
 * Log messages during development only.
 * Prefixes output with a `[DEV]` tag for clarity.
 *
 * @param {...any} args - Arguments to log
 */
/* eslint-env node */
/**
 * --- AUTO-GENERATED DOCSTRING ---
 * Table of content is automatically generated by Agent Docstrings v1.3.5
 *
 * Classes/Functions:
 *   - if (process.env.NODE_ENV !== 'production') (line 17)
 * --- END AUTO-GENERATED DOCSTRING ---
 */
export default function devLog(...args) {
  try {
    if (process.env.NODE_ENV !== "production") {
      console.log("[DEV]", ...args);
    }
  } catch (error) {
    if (process.env.NODE_ENV === "development") {
      console.error("Logger error:", error);
    }
  }
}
